#!/bin/sh

#SBATCH --mem=8g
#SBATCH --time=8:0:0
#SBATCH --output=/cs/labs/roys/aviadsa/cartography/slurm_out_files/WINOGRANDE/filter_slurm_out.txt

python cartography/selection/train_dy_filtering.py --filter --task_name abductive_nli --metric variability --bias 3 --model deberta-large --model_dir outputs/abductive_nli/deberta-large/huji_abductive_nli_deberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/abductive_nli  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name abductive_nli --metric variability --bias 3 --model electra-large --model_dir outputs/abductive_nli/electra-large/huji_abductive_nli_electra-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/abductive_nli  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name abductive_nli --metric variability --bias 3 --model roberta-large --model_dir outputs/abductive_nli/roberta-large/huji_abductive_nli_roberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/abductive_nli  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets

python cartography/selection/train_dy_filtering.py --filter --task_name anli_v1.0_R1 --metric variability --bias 3 --model deberta-large --model_dir outputs/anli_v1.0_R1/deberta-large/huji_anli_v1.0_R1_deberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/anli_v1.0_R1  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name anli_v1.0_R1 --metric variability --bias 3 --model electra-large --model_dir outputs/anli_v1.0_R1/electra-large/huji_anli_v1.0_R1_electra-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/anli_v1.0_R1  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name anli_v1.0_R1 --metric variability --bias 3 --model roberta-large --model_dir outputs/anli_v1.0_R1/roberta-large/huji_anli_v1.0_R1_roberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/anli_v1.0_R1  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets

python cartography/selection/train_dy_filtering.py --filter --task_name anli_v1.0_R3 --metric variability --bias 3 --model deberta-large --model_dir outputs/anli_v1.0_R3/deberta-large/huji_anli_v1.0_R3_deberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/anli_v1.0_R3  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name anli_v1.0_R3 --metric variability --bias 3 --model electra-large --model_dir outputs/anli_v1.0_R3/electra-large/huji_anli_v1.0_R3_electra-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/anli_v1.0_R3  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name anli_v1.0_R3 --metric variability --bias 3 --model roberta-large --model_dir outputs/anli_v1.0_R3/roberta-large/huji_anli_v1.0_R3_roberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/anli_v1.0_R3  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets

python cartography/selection/train_dy_filtering.py --filter --task_name SNLI --metric variability --bias 3 --model deberta-large --model_dir outputs/SNLI/deberta-large/huji_SNLI_deberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/SNLI  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name SNLI --metric variability --bias 3 --model electra-large --model_dir outputs/SNLI/electra-large/huji_SNLI_electra-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/SNLI  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name SNLI --metric variability --bias 3 --model roberta-large --model_dir outputs/SNLI/roberta-large/huji_SNLI_roberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/SNLI  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets

python cartography/selection/train_dy_filtering.py --filter --task_name WINOGRANDE --metric variability --bias 3 --model deberta-large --model_dir outputs/WINOGRANDE/deberta-large/huji_WINOGRANDE_deberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/WINOGRANDE  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name WINOGRANDE --metric variability --bias 3 --model electra-large --model_dir outputs/WINOGRANDE/electra-large/huji_WINOGRANDE_electra-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/WINOGRANDE  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets
python cartography/selection/train_dy_filtering.py --filter --task_name WINOGRANDE --metric variability --bias 3 --model roberta-large --model_dir outputs/WINOGRANDE/roberta-large/huji_WINOGRANDE_roberta-large_12_evals --data_dir /cs/labs/roys/aviadsa/datasets/cartography/WINOGRANDE  --plots_dir /cs/labs/roys/aviadsa/cartography/cartography/plots --filtering_output_dir /cs/labs/roys/aviadsa/datasets/cartography/filtered_datasets

